# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apocalypse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for apocalypse

  target 'apocalypse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'apocalypseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'apocalypse-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for apocalypse-tvOS

  target 'apocalypse-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
