# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'apocalypse' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for apocalypse
  pod 'Firebase/Core'
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # target 'apocalypse-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  #   pod 'react-native-video', :path => '../node_modules/react-native-video'

  #   pod 'react-native-music-control', :path => '../node_modules/react-native-music-control'

  # end

  target 'apocalypseTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'apocalypse-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for apocalypse-tvOS
# end
